### ISSUE TITLE
Dependency on typelevel scala-library 2.12.1

### ISSUE THREAD

**Issue by channingwalton** [davegurnell/bridges#2]
Hi,
we've had an issue when using the lib with scala 2.12.6 because scala-library 2.12.1 is on the classpath too.

The error we got was:

    java.lang.NoSuchMethodError: scala.util.Properties$.coloredOutputEnabled()Z

I don't know whether that is really "*our problem*" though.

**Comment by pvillega** [comment]
Fixed on release 0.8.1 👍
