### ISSUE TITLE
scala 2.13 support

### ISSUE THREAD

**Issue by fkowal** [davegurnell/bridges#25]
I'd like to bump the scala version for this project 2.13

I am waiting for the uident scala 2.13 update to be accepted https://github.com/davegurnell/unindent/issues/3

I am creating this issue hopeing this will reach @davegurnell

**Comment by davegurnell** [comment]
I still need 2.12 for a project. I’m definitely up for creating a cross-build, though, if that’s possible with the new collections API!

**Comment by fkowal** [comment]
I have a cross build for 2.12 and 2.13 working locally so I'd we can get unidentified merged we should be good to go

**Comment by davegurnell** [comment]
Awesome! IIRC unindent is only used in the tests. If the macro is heart supports I don’t mind dropping it or rewriting it as a regular runtime string interpolator.

--  
Dave Gurnell  
Underscore
https://underscore.io

**Comment by fkowal** [comment]
PR is ready https://github.com/davegurnell/bridges/pull/26

**Comment by davegurnell** [comment]
Merged. Cheers!
