### ISSUE TITLE
Support self-recursive types

### ISSUE THREAD

**Issue by davegurnell** [davegurnell/bridges#5]
Bridges currently infinite loops if you try to compile a type for a self-recursive data structure. For example:

~~~scala
case class OneAnd(head: Int, tail: Option[OneAnd])
~~~

I'm not sure why this happens. We shouldn't be recursing more than one layer deep into a struct definition. However, we clearly are!

**Comment by pvillega** [comment]
I thought this was due to the way Shapeless works (that's what I wrote in the blog post). I may be wrong :)

**Comment by davegurnell** [comment]
I modified the wording in the blog post. Lazy should allow you to do
recursive expansions, but we're not even supposed to be being recursive
here. I'm pretty sure it's just a bug somewhere in the derivation code.

**Comment by pvillega** [comment]
Probably linked to #6
