### ISSUE TITLE
First-class support for ADTs

### ISSUE THREAD

**Issue by davegurnell** [davegurnell/bridges#6]
I have a hunch the definition of `Intersection` is over-complicated. I need to review this with @pvillega.

**Comment by davegurnell** [comment]
After discussion with @pvillega, we reckon this should do it:

- Rename `Struct` to `Product`
- Add a first class `SumOfProducts`
- Generate `SumOfProducts` in ccons/cnilEncoder

to make them easier to handle in Elm.

Also, Elm doesn't have literal types or intersections. We should update `Renderer` et al so they return an `Either` (or `Validated`).

**Comment by pvillega** [comment]
Fixed by PR #18 (not sure why it didn't close this automatically)
